[Xorg_dri3proto]
git-tree-sha1 = "d3e505f59211b9a303bfd4a1d2826ddf2615b24c"

    [[Xorg_dri3proto.download]]
    sha256 = "edeeca929ef6dbc001447fee538ecee50af8d7a88158ca95ee18141bcb3d74fe"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_dri3proto_jll.jl/releases/download/Xorg_dri3proto-v1.0.0+1/Xorg_dri3proto.v1.0.0.any.tar.gz"
