# Autogenerated wrapper script for Xorg_dri3proto_jll for any
JLLWrappers.@generate_wrapper_header("Xorg_dri3proto")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@generate_init_footer()
end  # __init__()
